/**
 * Markdown output formatter for AI Code Security Scanner.
 *
 * Renders findings as a GitHub-flavored Markdown table suitable for inclusion
 * in pull request comments, issue descriptions, or CI summaries.
 *
 * Output format:
 *   - A header section with scan summary
 *   - A GFM table with: Severity | Type | File | Line | Message
 *   - Findings are grouped by severity (critical → high → medium → low)
 *   - A collapsible details block per finding with full message + snippet
 */

import type { Finding } from './reporter';

const SEVERITY_ORDER: Record<string, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
};

const SEVERITY_EMOJI: Record<string, string> = {
  critical: ':red_circle:',
  high: ':orange_circle:',
  medium: ':yellow_circle:',
  low: ':white_circle:',
};

function escapeMd(str: string): string {
  return str
    .replace(/\|/g, '\\|')
    .replace(/`/g, "'")
    .replace(/\n/g, ' ')
    .replace(/\r/g, '');
}

/**
 * Builds a GitHub-flavored Markdown report from a list of findings.
 *
 * @param findings   Deduplicated, filtered findings array.
 * @param targetPath The scan root path shown in the header.
 * @returns          A Markdown string ready to paste into a GitHub PR comment.
 */
export function buildMarkdownReport(findings: Finding[], targetPath: string): string {
  const lines: string[] = [];

  const total = findings.length;
  const bySeverity: Record<string, number> = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of findings) {
    bySeverity[f.severity] = (bySeverity[f.severity] ?? 0) + 1;
  }

  // Header
  lines.push('## AI Code Security Scanner Report');
  lines.push('');
  lines.push(`**Scanned:** \`${targetPath}\``);
  lines.push('');

  if (total === 0) {
    lines.push(':white_check_mark: **No findings** — no security issues detected.');
    return lines.join('\n');
  }

  // Summary badges
  const summaryParts: string[] = [];
  if (bySeverity.critical) summaryParts.push(`:red_circle: **${bySeverity.critical} critical**`);
  if (bySeverity.high) summaryParts.push(`:orange_circle: **${bySeverity.high} high**`);
  if (bySeverity.medium) summaryParts.push(`:yellow_circle: ${bySeverity.medium} medium`);
  if (bySeverity.low) summaryParts.push(`:white_circle: ${bySeverity.low} low`);
  lines.push(summaryParts.join(' &nbsp; ') + ` — **${total} total**`);
  lines.push('');

  // Sort by severity then file then line
  const sorted = [...findings].sort((a, b) => {
    const sevDiff = (SEVERITY_ORDER[a.severity] ?? 99) - (SEVERITY_ORDER[b.severity] ?? 99);
    if (sevDiff !== 0) return sevDiff;
    const fileDiff = (a.file ?? '').localeCompare(b.file ?? '');
    if (fileDiff !== 0) return fileDiff;
    return (a.line ?? 0) - (b.line ?? 0);
  });

  // Table
  lines.push('| Severity | Type | File | Line | Description |');
  lines.push('|---|---|---|---|---|');

  for (const f of sorted) {
    const emoji = SEVERITY_EMOJI[f.severity] ?? '';
    const severity = `${emoji} \`${f.severity}\``;
    const type = `\`${f.type}\``;
    const file = f.file ? `\`${escapeMd(f.file)}\`` : '—';
    const line = f.line != null ? String(f.line) : '—';
    const msg = escapeMd(f.message.slice(0, 120));
    lines.push(`| ${severity} | ${type} | ${file} | ${line} | ${msg} |`);
  }

  lines.push('');

  // Collapsible details for each finding
  lines.push('<details>');
  lines.push('<summary>Finding details</summary>');
  lines.push('');

  for (const f of sorted) {
    const emoji = SEVERITY_EMOJI[f.severity] ?? '';
    lines.push(`### ${emoji} \`${f.type}\` — ${f.file ?? 'unknown'}:${f.line ?? '?'}`);
    lines.push('');
    lines.push(`**Severity:** ${f.severity}`);
    if (f.confidence != null) {
      lines.push(`**Confidence:** ${Math.round(f.confidence * 100)}%`);
    }
    lines.push('');
    lines.push(f.message);
    lines.push('');
    if (f.snippet) {
      lines.push('```');
      lines.push(f.snippet);
      lines.push('```');
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  lines.push('</details>');
  lines.push('');
  lines.push(
    '_Generated by [AI Code Security Scanner](https://github.com/your-org/ai-code-security-scanner)_',
  );

  return lines.join('\n');
}
